// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps in HMG environment.
///
/// Example:
/// ```dart
/// import 'firebase_options_hmg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptionsHmg.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsHmg {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptionsHmg have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptionsHmg have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptionsHmg have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptionsHmg have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptionsHmg are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAZFWi74M4a7yYb1x2WN9TTqSHNKIyAqs',
    appId: '1:428326316592:android:5b9d70989591525b155bf5',
    messagingSenderId: '428326316592',
    projectId: 'base-app-hmg-1756753495',
    storageBucket: 'base-app-hmg-1756753495.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzskaPQ7kPO5JoVtlJ_P8CAjYjNqQlYPo',
    appId: '1:428326316592:ios:a9487a1a49a55816155bf5',
    messagingSenderId: '428326316592',
    projectId: 'base-app-hmg-1756753495',
    storageBucket: 'base-app-hmg-1756753495.firebasestorage.app',
    iosBundleId: 'com.example.baseapp.hmg',
  );
}
